### ISSUE TITLE
Error: doesn't find all queries

### ISSUE THREAD

**Issue by csillag** [apollographql/graphql-document-collector#7] opened 2017-03-02 09:28 UTC
I might have found a problem, where `graphql-document-collector` doesn't find all the .graphql files.

This is the directory structure:

```
./graphql
./graphql/getWorker.graphql
./ui
./ui/components
./ui/components/AlarmIndicator.graphql
```

I am running this command:

```
graphql-document-collector  ./**/*.graphql
```

The resulting JSON contains only the query parsed from `getWorker.graphql`, but not the one parsed from `AlarmIndicator.graphql`.

However, if I remove the `getWorker.graphql` file, the tool *will* find the other file.

So it seems like it starts parsing one file, and the forgets about the rest?
(Maybe a problem with the async parsing of files.)

Could you please look into this?
Thanks.

**Comment by csillag** [comment] 2017-03-02 10:10
One more note: in the same app, [apollo-codegen](https://github.com/apollographql/apollo-codegen) finds and parses all the `.graphql` files correctly.

**Comment by madebyherzblut** [comment] 2017-06-02 16:59
I just ran into this problem as well and it was caused by the automatic expansion of glob patterns in my shell (e. g. zsh). You might want to try `graphql-document-collector  "./**/*.graphql"` and see if that fixes you issue.

**Comment by yuricamara** [comment] 2017-08-25 22:05
I had the same problem and I solved it with your tip, @madebyherzblut .
Thanks!

**Comment by stephen** [comment] 2017-12-20 06:25
Closing this issue, since it looks like there is resolution!

**Closed by stephen** 2017-12-20 06:25 UTC
